# Principal Component Analysis (PCA)

In [1]:
import numpy as np
import pandas as pd

# Import the dataset
df = pd.read_csv('sample_data/california_housing_train.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [2]:
# X = df[['total_rooms', 'households',	'median_income']]
X = df.drop(['total_bedrooms'], axis=1)
y = df['total_bedrooms']
X

longitude  latitude  housing_median_age  total_rooms  population  \
0        -114.31     34.19                15.0       5612.0      1015.0   
1        -114.47     34.40                19.0       7650.0      1129.0   
2        -114.56     33.69                17.0        720.0       333.0   
3        -114.57     33.64                14.0       1501.0       515.0   
4        -114.57     33.57                20.0       1454.0       624.0   
...          ...       ...                 ...          ...         ...   
16995    -124.26     40.58                52.0       2217.0       907.0   
16996    -124.27     40.69                36.0       2349.0      1194.0   
16997    -124.30     41.84                17.0       2677.0      1244.0   
16998    -124.30     41.80                19.0       2672.0      1298.0   
16999    -124.35     40.54                52.0       1820.0       806.0   

       households  median_income  median_house_value  
0           472.0         1.4936             66900.0  
1           463.0         1.8200             80100.0  
2           117.0         1.6509             85700.0  
3           226.0         3.1917             73400.0  
4           262.0         1.9250             65500.0  
...           ...            ...                 ...  
16995       369.0         2.3571            111400.0  
16996       465.0         2.5179             79000.0  
16997       456.0         3.0313            103600.0  
16998       478.0         1.9797             85800.0  
16999       270.0         3.0147             94600.0  

[17000 rows x 8 columns]

# PCA SKLearn

In [3]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# create the PCA instance
pca = PCA(8)
# fit on data
pca.fit(X)


PCA(n_components=8)

In [4]:
# access values and vectors
print(pca.explained_variance_)


[1.34523167e+10 5.85965044e+06 2.60340477e+05 1.44857840e+04
 1.32460650e+02 7.96920001e+00 1.36925438e+00 2.10577241e-01]


In [5]:
print(pca.components_)

[[-7.77617996e-07 -2.67051766e-06  1.15838398e-05  2.46283574e-03
  -2.75247158e-04  2.02467962e-04  1.13826486e-05  9.99996909e-01]
 [ 5.34403360e-05 -3.63724044e-05 -1.91144227e-03  8.87684680e-01
   4.35556407e-01  1.49326716e-01  6.83752690e-05 -2.09655494e-03]
 [ 4.04190206e-04 -8.24054637e-04  2.87094035e-03 -4.51829235e-01
   8.86422150e-01  1.00473138e-01 -6.27133248e-04  1.33639990e-03]
 [ 6.49824093e-04  6.27899605e-05 -7.12351280e-03  8.85794803e-02
   1.56668850e-01 -9.83633077e-01  4.83168908e-03  2.41483985e-05]
 [-1.89398862e-02  8.95718723e-03  9.99515802e-01  3.63548751e-03
  -5.75299958e-04 -7.12063959e-03 -2.15629367e-02 -1.89939109e-05]
 [-6.89552948e-01  7.23964846e-01 -1.96074682e-02 -3.72879477e-04
   8.78751172e-04 -1.73216216e-04 -2.49775765e-03  2.84800719e-06]
 [-7.29617486e-03 -2.91710513e-03  2.14908845e-02 -6.93659030e-04
  -2.42207147e-04  4.64905566e-03  9.99727085e-01 -1.09415701e-05]
 [ 7.23950405e-01  6.89772047e-01  7.69486429e-03 -1.59814624e-04
   

In [6]:
# transform data
X_pca = pca.transform(X)
print(X_pca)

[[-1.40393060e+05  2.74439644e+03 -1.89927032e+03 ... -6.25417641e+00
  -3.27375467e+00  1.77806154e+00]
 [-1.27188114e+05  4.57412515e+03 -2.70229891e+03 ... -6.69165856e+00
  -4.48848436e+00  1.56107039e+00]
 [-1.21605050e+05 -1.98763650e+03 -3.03999298e+02 ... -5.14352604e+00
  -1.36778426e+00  1.81367839e+00]
 ...
 [-1.03700468e+05  1.59447003e+02 -3.22728099e+02 ...  7.53266148e+00
  -1.38436328e-01  4.38740145e-01]
 [-1.21500436e+05  2.19128598e+02 -2.94173231e+02 ...  7.46192627e+00
  -8.59222595e-01  3.93605655e-01]
 [-1.12702467e+05 -8.01045105e+02 -3.54377404e+02 ...  5.88101576e+00
   5.35608503e-01 -2.72713982e-01]]


# PCA from Scratch

In [7]:
from numpy import array, mean, cov
from numpy.linalg import eig

In [8]:
# calculate the mean of each column
M = mean(X, axis = 0)
M

longitude               -119.562108
latitude                  35.625225
housing_median_age        28.589353
total_rooms             2643.664412
population              1429.573941
households               501.221941
median_income              3.883578
median_house_value    207300.912353
dtype: float64

In [9]:
# center columns by subtracting column means
C = X - M
C

longitude  latitude  housing_median_age  total_rooms   population  \
0       5.252108 -1.435225          -13.589353  2968.335588  -414.573941   
1       5.092108 -1.225225           -9.589353  5006.335588  -300.573941   
2       5.002108 -1.935225          -11.589353 -1923.664412 -1096.573941   
3       4.992108 -1.985225          -14.589353 -1142.664412  -914.573941   
4       4.992108 -2.055225           -8.589353 -1189.664412  -805.573941   
...          ...       ...                 ...          ...          ...   
16995  -4.697892  4.954775           23.410647  -426.664412  -522.573941   
16996  -4.707892  5.064775            7.410647  -294.664412  -235.573941   
16997  -4.737892  6.214775          -11.589353    33.335588  -185.573941   
16998  -4.737892  6.174775           -9.589353    28.335588  -131.573941   
16999  -4.787892  4.914775           23.410647  -823.664412  -623.573941   

       households  median_income  median_house_value  
0      -29.221941      -2.389978      -140400.912353  
1      -38.221941      -2.063578      -127200.912353  
2     -384.221941      -2.232678      -121600.912353  
3     -275.221941      -0.691878      -133900.912353  
4     -239.221941      -1.958578      -141800.912353  
...           ...            ...                 ...  
16995 -132.221941      -1.526478       -95900.912353  
16996  -36.221941      -1.365678      -128300.912353  
16997  -45.221941      -0.852278      -103700.912353  
16998  -23.221941      -1.903878      -121500.912353  
16999 -231.221941      -0.868878      -112700.912353  

[17000 rows x 8 columns]

In [10]:
# calculate covariance matrix of centered matrix
V = cov(C, rowvar = False)
V

array([[ 4.02069233e+00, -3.96518544e+00, -2.88355242e+00,
         2.05489998e+02,  2.34017167e+02,  4.59746458e+01,
        -5.92481156e-02, -1.04612469e+04],
       [-3.96518544e+00,  4.56822140e+00,  4.42652137e-01,
        -1.80652575e+02, -2.72963262e+02, -6.15585795e+01,
        -3.27506114e-01, -3.59243782e+04],
       [-2.88355242e+00,  4.42652137e-01,  1.58430983e+02,
        -9.90499269e+03, -4.27500196e+03, -1.46531200e+03,
        -2.78442789e+00,  1.55853477e+05],
       [ 2.05489998e+02, -1.80652575e+02, -9.90499269e+03,
         4.75216923e+06,  2.15236872e+06,  7.70353377e+05,
         8.12729998e+02,  3.31196816e+07],
       [ 2.34017167e+02, -2.72963262e+02, -4.27500196e+03,
         2.15236872e+06,  1.31756642e+06,  4.01317219e+05,
        -1.39658833e+00, -3.70774289e+06],
       [ 4.59746458e+01, -6.15585795e+01, -1.46531200e+03,
         7.70353377e+05,  4.01317219e+05,  1.47856277e+05,
         5.60839292e+00,  2.72185486e+06],
       [-5.92481156e-02, -3.275061

In [11]:
# eigendecomposition of covariance matrix
eigval, eigvec = eig(V)

In [12]:
eigval

array([1.34523167e+10, 5.85965044e+06, 2.60340477e+05, 1.44857840e+04,
       1.32460650e+02, 7.96920001e+00, 2.10577240e-01, 1.36925438e+00])

In [13]:
eigvec

array([[-7.77617997e-07, -5.34403360e-05,  4.04190206e-04,
        -6.49824093e-04, -1.89398863e-02,  6.89552949e-01,
         7.23950405e-01, -7.29617485e-03],
       [-2.67051766e-06,  3.63724044e-05, -8.24054637e-04,
        -6.27899608e-05,  8.95718723e-03, -7.23964846e-01,
         6.89772047e-01, -2.91710513e-03],
       [ 1.15838398e-05,  1.91144227e-03,  2.87094035e-03,
         7.12351280e-03,  9.99515802e-01,  1.96074682e-02,
         7.69486429e-03,  2.14908845e-02],
       [ 2.46283574e-03, -8.87684680e-01, -4.51829235e-01,
        -8.85794803e-02,  3.63548751e-03,  3.72879477e-04,
        -1.59814624e-04, -6.93659030e-04],
       [-2.75247158e-04, -4.35556407e-01,  8.86422150e-01,
        -1.56668850e-01, -5.75299958e-04, -8.78751172e-04,
         1.51827143e-04, -2.42207147e-04],
       [ 2.02467962e-04, -1.49326716e-01,  1.00473138e-01,
         9.83633077e-01, -7.12063959e-03,  1.73216216e-04,
         5.11378633e-04,  4.64905566e-03],
       [ 1.13826486e-05, -6.837526

In [14]:
#sort the eigenvalues in descending order
sorted_index = np.argsort(eigval)[::-1]
sorted_index


array([0, 1, 2, 3, 4, 5, 7, 6])

In [15]:
sorted_eigenvalue = eigval[sorted_index]
sorted_eigenvalue


array([1.34523167e+10, 5.85965044e+06, 2.60340477e+05, 1.44857840e+04,
       1.32460650e+02, 7.96920001e+00, 1.36925438e+00, 2.10577240e-01])

In [16]:
#similarly sort the eigenvectors
sorted_eigenvectors = eigvec[:,sorted_index]
sorted_eigenvectors

array([[-7.77617997e-07, -5.34403360e-05,  4.04190206e-04,
        -6.49824093e-04, -1.89398863e-02,  6.89552949e-01,
        -7.29617485e-03,  7.23950405e-01],
       [-2.67051766e-06,  3.63724044e-05, -8.24054637e-04,
        -6.27899608e-05,  8.95718723e-03, -7.23964846e-01,
        -2.91710513e-03,  6.89772047e-01],
       [ 1.15838398e-05,  1.91144227e-03,  2.87094035e-03,
         7.12351280e-03,  9.99515802e-01,  1.96074682e-02,
         2.14908845e-02,  7.69486429e-03],
       [ 2.46283574e-03, -8.87684680e-01, -4.51829235e-01,
        -8.85794803e-02,  3.63548751e-03,  3.72879477e-04,
        -6.93659030e-04, -1.59814624e-04],
       [-2.75247158e-04, -4.35556407e-01,  8.86422150e-01,
        -1.56668850e-01, -5.75299958e-04, -8.78751172e-04,
        -2.42207147e-04,  1.51827143e-04],
       [ 2.02467962e-04, -1.49326716e-01,  1.00473138e-01,
         9.83633077e-01, -7.12063959e-03,  1.73216216e-04,
         4.64905566e-03,  5.11378633e-04],
       [ 1.13826486e-05, -6.837526

In [19]:
# select the first n eigenvectors, n is desired dimension
# of our final reduced data.

n_components = 2 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
eigenvector_subset

array([[-7.77617997e-07, -5.34403360e-05],
       [-2.67051766e-06,  3.63724044e-05],
       [ 1.15838398e-05,  1.91144227e-03],
       [ 2.46283574e-03, -8.87684680e-01],
       [-2.75247158e-04, -4.35556407e-01],
       [ 2.02467962e-04, -1.49326716e-01],
       [ 1.13826486e-05, -6.83752690e-05],
       [ 9.99996909e-01,  2.09655494e-03]])

In [20]:
#Transform the data
X_reduced = np.dot(eigenvector_subset.transpose(),C.transpose()).transpose()
X_reduced

array([[-140393.05980005,   -2744.39644378],
       [-127188.11449671,   -4574.12514583],
       [-121605.05023995,    1987.63650245],
       ...,
       [-103700.46791664,    -159.44700284],
       [-121500.43560347,    -219.12859775],
       [-112702.46743722,     801.04510547]])